Fix missing header file
source/event.c:389:16: error: implicit declaration of function 'GetBlueUnitByPid'; did you mean 'GetUnitByPid'? [-Wimplicit-function-declaration]
  389 |         unit = GetBlueUnitByPid(info->pid);
      |                ^~~~~~~~~~~~~~~~
      |                GetUnitByPid